# Generated by Django 4.0.4 on 2022-04-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=100),
        ),
    ]
