# Generated by Django 4.0.4 on 2022-04-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
